/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.util.Scanner;

public class App {
    private Predio predio;
    public void impressaoElevadorSubindo(int andar) throws InterruptedException {
        predio.getElevador().getCentralDeControle().setDirecao("subindo");
        for (int i = predio.getElevador().getCentralDeControle().getAndarAtualElevador(); i <= andar; i++) {
            if(i == andar){
                predio.getElevador().pararElevador();
                predio.getElevador().getCentralDeControle().getPaineis().get(andar).desativarBotaoSubir();
                predio.getElevador().getCentralDeControle().getPainelInterno().desativarAndar(andar);
            }
            if(predio.getElevador().getCentralDeControle().getAndarAtualElevador() == 0){
                System.out.print("Elevador | Andar atual: T");
            }else {
                System.out.print("Elevador | Andar atual: " + predio.getElevador().getCentralDeControle().getAndarAtualElevador());
            }
            System.out.println(" | Direção: " + predio.getElevador().getCentralDeControle().getDirecao());
            System.out.print("Botões: ");
            for (int j = 0; j < predio.getNumAndares(); j++) {
                if(j == 0) {
                    System.out.print("T " + "(" + predio.getElevador().getCentralDeControle().getPainelInterno().getBotoes().get(j).getEstado() + ")");
                } else {
                    System.out.print(" " + j + "(" + predio.getElevador().getCentralDeControle().getPainelInterno().getBotoes().get(j).getEstado() + ")");
                }
            }
            System.out.print("\n");
            for (int j = 0; j < predio.getNumAndares(); j++) {
                if(j == 0){
                    System.out.print("Térreo:   " + " Elevador: " + predio.getElevador().getCentralDeControle().getDirecao());
                    System.out.println(" | Andar: " + predio.getElevador().getCentralDeControle().getAndarAtualElevador() + " | Botões: subir (" + predio.getElevador().getCentralDeControle().getPaineis().get(j).getSubir().getEstado() +
                            ") descer (" + predio.getElevador().getCentralDeControle().getPaineis().get(j).getDescer().getEstado() + ")");
                }else {
                    System.out.print(j + "o  Andar:" + " Elevador: " + predio.getElevador().getCentralDeControle().getDirecao());
                    System.out.println(" | Andar: " + predio.getElevador().getCentralDeControle().getAndarAtualElevador() + " | Botões: subir (" + predio.getElevador().getCentralDeControle().getPaineis().get(j).getSubir().getEstado() +
                            ") descer (" + predio.getElevador().getCentralDeControle().getPaineis().get(j).getDescer().getEstado() + ")");
                }
            }
            if(i < andar) {
                predio.getElevador().subirElevador();
            }
            System.out.print("\n");
            Thread.sleep(1000);
        }
    }

   public void impressaoElevadorDescendo(int andar) throws InterruptedException {
       predio.getElevador().getCentralDeControle().setDirecao("descendo");
       for (int i = predio.getElevador().getCentralDeControle().getAndarAtualElevador(); i >= andar; i--) {
           if(i == andar){
               predio.getElevador().pararElevador();
               predio.getElevador().getCentralDeControle().getPaineis().get(andar).desativarBotaoDescer();
               predio.getElevador().getCentralDeControle().getPainelInterno().desativarAndar(andar);
           }
           if(predio.getElevador().getCentralDeControle().getAndarAtualElevador() == 0){
               System.out.print("Elevador | Andar atual: T");
           }else {
               System.out.print("Elevador | Andar atual: " + predio.getElevador().getCentralDeControle().getAndarAtualElevador());
           }
           System.out.println(" | Direção: " + predio.getElevador().getCentralDeControle().getDirecao());
           System.out.print("Botões: ");
           for (int j = 0; j < predio.getNumAndares(); j++) {
               if(j == 0) {
                   System.out.print("T " + "(" + predio.getElevador().getCentralDeControle().getPainelInterno().getBotoes().get(j).getEstado() + ")");
               } else {
                   System.out.print(" " + j + "(" + predio.getElevador().getCentralDeControle().getPainelInterno().getBotoes().get(j).getEstado() + ")");
               }
           }
           System.out.print("\n");
           for (int j = 0; j < predio.getNumAndares(); j++) {
               if(j == 0){
                   System.out.print("Térreo:   " + " Elevador: " + predio.getElevador().getCentralDeControle().getDirecao());
                   System.out.println(" | Andar: " + predio.getElevador().getCentralDeControle().getAndarAtualElevador() + " | Botões: subir (" + predio.getElevador().getCentralDeControle().getPaineis().get(j).getSubir().getEstado() +
                           ") descer (" + predio.getElevador().getCentralDeControle().getPaineis().get(j).getDescer().getEstado() + ")");
               }else {
                   System.out.print(j + "o  Andar:" + " Elevador: " + predio.getElevador().getCentralDeControle().getDirecao());
                   System.out.println(" | Andar: " + predio.getElevador().getCentralDeControle().getAndarAtualElevador() + " | Botões: subir (" + predio.getElevador().getCentralDeControle().getPaineis().get(j).getSubir().getEstado() +
                           ") descer (" + predio.getElevador().getCentralDeControle().getPaineis().get(j).getDescer().getEstado() + ")");
               }
           }
           if(i > andar) {
               predio.getElevador().descerElevador();
           }
           System.out.print("\n");
           Thread.sleep(1000);
       }
   }

    public void impressaoPainelInterno (){
        System.out.println("\n| PAINEL ELEVADOR |");
        for (int i = 0; i < predio.getNumAndares(); i++) {
            System.out.print("| " + i + " | ");
        }
        System.out.print("\n\n");
    }

    public void imprimirOpcoesAndares(){

        for (int i = 0; i < predio.getNumAndares(); i++) {
            System.out.print("| " + i + " | ");
        }
        System.out.print("\n\n");
    }

    public void impressaoPainelExterno (int andar){
        if(andar == 0){
            System.out.println("| PAINEL EXTERNO - TÉRREO |");
            System.out.println("|    subir   | |   descer   |\n");
        }else{
            System.out.println("| PAINEL EXTERNO - " + andar + "o ANDAR |");
            System.out.println("|    subir   | |   descer   |\n");
        }

    }

    public void impressaoLetreiro(){
        System.out.println("\n");
        System.out.println("======================================");
        System.out.println(".....::PRÉDIO ORQUÍDEAS BRANCAS::.....");
        System.out.println("======================================");
    }

    public static void main(String[] args) throws InterruptedException {
        App app = new App();
        Scanner teclado = new Scanner(System.in);

        System.out.println("========================================");
        System.out.println("..:: SIMULADOR DE ELEVADOR IFSC-POO ::..");
        System.out.println("========================================");
        System.out.print("ENTRE COM O NÚMERO DE ANDARES: ");

        int numAndares = teclado.nextInt();
        teclado.nextLine();
        app.predio = new Predio(numAndares);

        String op = null;
        System.out.print("\n");
        System.out.println("ANDAR INICIAL DO ELEVADOR - TÉRREO");

        do {
                System.out.print("\nVOCÊ ESTÁ DENTRO OU FORA DO ELEVADOR: ");
                op = teclado.nextLine();
                int andarSel = 0;
                System.out.print("\n");

                if (op.equals("dentro") || op.equals("DENTRO")) {
                    app.impressaoLetreiro();
                    System.out.println("\nSELECIONE O ANDAR:");
                    app.impressaoPainelInterno();

                    System.out.print("ANDAR:");
                    andarSel = teclado.nextInt();
                    teclado.nextLine();
                    System.out.print("\n");

                    if (andarSel == app.predio.getElevador().getCentralDeControle().getAndarAtualElevador()) {
                        System.out.println("VOCÊ JÁ ESTÁ NO " + app.predio.getElevador().getCentralDeControle().getAndarAtualElevador() + "o ANDAR\n");
                    } else if (andarSel > app.predio.getNumAndares() - 1 || app.predio.getElevador().getCentralDeControle().getAndarAtualElevador() == app.predio.getNumAndares() || andarSel < 0) {
                        System.out.println("OPÇÃO INVÁLIDA! TENTE NOVAMENTE\n");
                    }else{
                        if(andarSel > app.predio.getElevador().getCentralDeControle().getAndarAtualElevador()) {
                            app.predio.getElevador().getCentralDeControle().getPainelInterno().ativarAndar(andarSel);
                            app.impressaoElevadorSubindo(andarSel);
                            System.out.println("VOCÊ CHEGOU AO " + andarSel + "o ANDAR\n");
                        }else{
                            app.predio.getElevador().getCentralDeControle().getPainelInterno().ativarAndar(andarSel);
                            app.impressaoElevadorDescendo(andarSel);
                            if(app.predio.getElevador().getCentralDeControle().getAndarAtualElevador() == 0){
                                System.out.println("VOCÊ CHEGOU AO TÉRREO\n");
                            }else {
                                System.out.println("VOCÊ CHEGOU AO " + andarSel + "o ANDAR\n");
                            }
                        }
                    }
                } else if (op.equals("fora") || op.equals("FORA")) {
                    app.imprimirOpcoesAndares();

                    System.out.print("ENTRE COM SEU ANDAR ATUAL: ");
                    int andarAtualUsuario = teclado.nextInt();
                    teclado.nextLine();
                    if(andarAtualUsuario > app.predio.getNumAndares()  - 1|| andarAtualUsuario < 0){
                        System.out.println("OPÇÃO INVÁLIDA! TENTE NOVAMENTE");
                    }else {

                        app.impressaoPainelExterno(andarAtualUsuario);

                        System.out.print("CHAMAR ELEVADOR: ");
                        op = teclado.nextLine();
                        if (andarAtualUsuario == app.predio.getElevador().getCentralDeControle().getAndarAtualElevador()) {
                            System.out.println("O ELEVADOR ESTÁ NO SEU ANDAR ATUAL");
                        } else {
                            if (op.equals("subir") && andarAtualUsuario > app.predio.getElevador().getCentralDeControle().getAndarAtualElevador()) {
                                app.predio.getElevador().getCentralDeControle().getPaineis().get(andarAtualUsuario).ativarBotaoSubir();
                                app.impressaoElevadorSubindo(andarAtualUsuario);
                                System.out.println("O ELEVADOR CHEGOU AO SEU ANDAR\n");
                            } else if (op.equals("subir") && andarAtualUsuario < app.predio.getElevador().getCentralDeControle().getAndarAtualElevador()) {
                                System.out.println("O ELEVADOR ESTÁ ACIMA DO SEU ANDAR ATUAL\n");
                            } else if (op.equals("descer") && andarAtualUsuario < app.predio.getElevador().getCentralDeControle().getAndarAtualElevador()) {
                                app.predio.getElevador().getCentralDeControle().getPaineis().get(andarAtualUsuario).ativarBotaoDescer();
                                app.impressaoElevadorDescendo(andarAtualUsuario);
                                System.out.println("O ELEVADOR CHEGOU AO SEU ANDAR\n");
                            } else if (op.equals("descer") && andarAtualUsuario > app.predio.getElevador().getCentralDeControle().getAndarAtualElevador()) {
                                System.out.println("O ELEVADOR ESTÁ ABAIXO DO SEU ANDAR ATUAL\n");
                            } else {
                                System.out.println("OPÇÃO INVÁLIDA! TENTE NOVAMENTE\n");
                            }
                        }
                    }
                } else{
                    System.out.println("OPÇÃO INVÁLIDA! TENTE NOVAMENTE\n");
                }

            System.out.print("DIGITE 'sair' PARA FINALIZAR A SIMULAÇÃO OU PRECIONE A TECLA ENTER PARA CONTINUAR:");
            op = teclado.nextLine();
        }while(!op.equals("sair"));

        teclado.close();
    }
}
